# story config

valine:
  API_ID: GyC3NzMvd0hT9Yyd2hYIC0MN-gzGzoHsz
  API_Key: mgOpfzbkHYqU92CV4IDlAUHQ

tocbot:
  contentSelector: .post-content
  scrollSmooth: true
  headingSelector: h1, h2, h3, h4, h5
  headingsOffset: 45
  scrollSmoothOffset: -45